FROM alpine

RUN apk update && apk add vim
RUN apk add php7-common php7-iconv php7-json php7-curl \
    php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql \
    php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom \
    php7 php7-fpm php7-opcache php7-session php7-mbstring php7-gd php7-zlib php7-redis

RUN mkdir -p /www
RUN cd /www && wget http://wordpress.org/latest.tar.gz && tar -xzvf latest.tar.gz && rm latest.tar.gz

COPY ./conf/wp-config.php /www/wordpress/wp-config.php

RUN sed -i 's/listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/' /etc/php7/php-fpm.d/www.conf
RUN sed -i 's/user = nobody/user = root/g'  /etc/php7/php-fpm.d/www.conf

COPY ./tools/script.sh /
RUN chmod +x script.sh
CMD ./script.sh
