FROM php:5.6-apache

RUN docker-php-ext-install mysqli

# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli



FROM wordpress

# Set environment variables used by the Wordpress image
# DB_USER and DB_PASSWORD are included as an example. However,
# these should be removed and set during docker run.
ENV WORDPRESS_DB_HOST=mymysql \
    WORDPRESS_DB_USER=wpuser \
    WORDPRESS_DB_PASSWORD=super-secret-password \
    WORDPRESS_DB_NAME=wpsite \
    WORDPRESS_TABLE_PREFIX=wp_

# COPY plugins/ /var/www/html/wp-content/plugins
# COPY themes/ /var/www/html/wp-content/themes
# COPY uploads/ /var/www/html/wp-content/uploads


# EXPOSE 8080
